### ISSUE TITLE
coordenadas geográficas dos reservatórios

### ISSUE THREAD

**Issue by rafapereirabr** [brunomioto/reservatoriosBR#17]
Oi Bruno. Parabens pelo pacote. Você tem previsão de incluir os dados das coordenadas geográficas dos reservatórios? Eu tinha pensando em incluir esse tipo de dado no [geobr](https://github.com/ipeaGIT/geobr), mas nunca tive tempo. Seria ótimo ter essas informações no `reservatoriosBR` ou no `geobr`.

ps. eu também gostaria de incluir alguns dados de recursos hídricos da ANA no geobr, mas tenho pouca familiariedade com os dados. Seria ótimo se você quiser colaborar com isso no geobr.

**Comment by brunomioto** [comment]
Opa Rafael, fico feliz que o pacote tenha chegado até vocês do `geobr`!
Sobre as coordenadas, eu até consegui de diversos reservatórios, mas acabei deixando para uma próxima atualização do pacote (que preciso revisar as fontes e citar certinho). Inclusive retirei as coordenadas de um shapefile.. Agora que lancei os dados da ONS, que eu julguei serem mais importantes para o momento, vou dar uma olhada nisso.

Em relação aos dados de recursos hídricos da ANA, fico à disposição!

**Comment by brunomioto** [comment]
> Oi Bruno. Parabens pelo pacote. Você tem previsão de incluir os dados das coordenadas geográficas dos reservatórios? Eu tinha pensando em incluir esse tipo de dado no [geobr](https://github.com/ipeaGIT/geobr), mas nunca tive tempo. Seria ótimo ter essas informações no `reservatoriosBR` ou no `geobr`.
> 
> ps. eu também gostaria de incluir alguns dados de recursos hídricos da ANA no geobr, mas tenho pouca familiariedade com os dados. Seria ótimo se você quiser colaborar com isso no geobr.

Fala @rafapereirabr , tudo certo?
Consegui a tabela dos reservatórios com a ANA, com 713 reservatórios. E com as coordenadas de cada um!
Assim que possível publicarei a nova versão do pacote com esses dados!

**Comment by rafapereirabr** [comment]
Oi Bruno. Que ótimo. Acho que faz todo sentido esses dados dos reservatórios estarem no seu pacote. Daí acho q nao precisa incluir no geobr tambem
